import type { PR, WorkspaceInfo } from "../shared/model";
export const pr = (overrides: Partial<PR> = {}): PR => ({
  id: "PR_1",
  repoId: "R_1",
  repo: "org/repo",
  number: 1,
  url: "https://github.com/org/repo/pull/1",
  title: "Change",
  author: "alice",
  state: "open",
  headRepo: "alice/repo",
  headRef: "feature",
  headSha: "a".repeat(40),
  baseRepo: "org/repo",
  baseRef: "main",
  baseSha: "b".repeat(40),
  trunk: "main",
  mergeable: true,
  signals: [],
  seen: [],
  initialized: true,
  unread: 0,
  updatedAt: "2026-01-01",
  ...overrides,
});
export const workspace = (overrides: Partial<WorkspaceInfo> = {}): WorkspaceInfo => ({
  id: "w1",
  projectId: "p1",
  directory: "/example/repository",
  name: "example",
  branch: "feature",
  sha: "a".repeat(40),
  remotes: ["org/repo", "alice/repo"],
  headRemote: "alice/repo",
  dirty: false,
  operation: false,
  commonDir: "/example/repository/.git",
  checkoutRoot: "/example/repository",
  ...overrides,
});
